//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWorksSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public string Author { get; set; }
        public int Work { get; set; }
        public string Comment { get; set; }
        public int Scores { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Work Work1 { get; set; }
    }
}
